// 國八下 vocabulary - appended to window.vocabularyData
// Call this AFTER vocabulary.js loads
(function(){
  var g8b = [
    // Unit 1
    {"word":"foreign","def":"外國的","type":"adj.","book":"國八下","unit":"U1"},
    {"word":"than","def":"比","type":"prep.","book":"國八下","unit":"U1"},
    {"word":"friendly","def":"友善的","type":"adj.","book":"國八下","unit":"U1"},
    {"word":"convenient","def":"方便的","type":"adj.","book":"國八下","unit":"U1"},
    {"word":"pork","def":"豬肉","type":"n.","book":"國八下","unit":"U1"},
    {"word":"beef","def":"牛肉","type":"n.","book":"國八下","unit":"U1"},
    {"word":"delicious","def":"美味的","type":"adj.","book":"國八下","unit":"U1"},
    {"word":"feel","def":"感到","type":"v.","book":"國八下","unit":"U1"},
    {"word":"sound","def":"聽起來","type":"v.","book":"國八下","unit":"U1"},
    {"word":"menu","def":"菜單","type":"n.","book":"國八下","unit":"U1"},
    {"word":"waitress","def":"女服務生","type":"n.","book":"國八下","unit":"U1"},
    {"word":"ham","def":"火腿","type":"n.","book":"國八下","unit":"U1"},
    {"word":"butter","def":"奶油","type":"n.","book":"國八下","unit":"U1"},
    {"word":"medium","def":"五分熟；中等的","type":"adj.","book":"國八下","unit":"U1"},
    {"word":"meat","def":"肉","type":"n.","book":"國八下","unit":"U1"},
    {"word":"smell","def":"聞起來；氣味","type":"v./n.","book":"國八下","unit":"U1"},
    {"word":"taste","def":"嚐起來；味道","type":"v./n.","book":"國八下","unit":"U1"},
    {"word":"steak","def":"牛排；肉排","type":"n.","book":"國八下","unit":"U1"},
    {"word":"fries","def":"薯條","type":"n.","book":"國八下","unit":"U1"},
    {"word":"knife","def":"刀子","type":"n.","book":"國八下","unit":"U1"},
    {"word":"fork","def":"叉子","type":"n.","book":"國八下","unit":"U1"},
    {"word":"noodle","def":"麵","type":"n.","book":"國八下","unit":"U1"},
    {"word":"chopsticks","def":"筷子","type":"n.","book":"國八下","unit":"U1"},
    {"word":"spoon","def":"湯匙","type":"n.","book":"國八下","unit":"U1"},
    {"word":"waiter","def":"男服務生","type":"n.","book":"國八下","unit":"U1"},
    {"word":"strawberry","def":"草莓","type":"n.","book":"國八下","unit":"U1"},
    {"word":"bun","def":"小圓麵包","type":"n.","book":"國八下","unit":"U1"},
    {"word":"comfortable","def":"舒適的；自在的","type":"adj.","book":"國八下","unit":"U1"},
    {"word":"flavor","def":"口味","type":"n.","book":"國八下","unit":"U1"},
    {"word":"dish","def":"菜餚","type":"n.","book":"國八下","unit":"U1"},
    // Unit 2
    {"word":"grass","def":"草地","type":"n.","book":"國八下","unit":"U2"},
    {"word":"dangerous","def":"危險的","type":"adj.","book":"國八下","unit":"U2"},
    {"word":"bite","def":"咬；咬傷","type":"v./n.","book":"國八下","unit":"U2"},
    {"word":"death","def":"死亡","type":"n.","book":"國八下","unit":"U2"},
    {"word":"kill","def":"殺死","type":"v.","book":"國八下","unit":"U2"},
    {"word":"protect","def":"保護","type":"v.","book":"國八下","unit":"U2"},
    {"word":"agree","def":"同意","type":"v.","book":"國八下","unit":"U2"},
    {"word":"cause","def":"造成","type":"v.","book":"國八下","unit":"U2"},
    {"word":"nest","def":"巢；窩","type":"n.","book":"國八下","unit":"U2"},
    {"word":"scary","def":"令人害怕的","type":"adj.","book":"國八下","unit":"U2"},
    {"word":"outdoor","def":"戶外的","type":"adj.","book":"國八下","unit":"U2"},
    {"word":"safety","def":"安全","type":"n.","book":"國八下","unit":"U2"},
    {"word":"insect","def":"昆蟲","type":"n.","book":"國八下","unit":"U2"},
    {"word":"bee","def":"蜜蜂","type":"n.","book":"國八下","unit":"U2"},
    {"word":"smart","def":"聰明的","type":"adj.","book":"國八下","unit":"U2"},
    {"word":"traffic","def":"交通；車流量","type":"n.","book":"國八下","unit":"U2"},
    {"word":"accident","def":"意外","type":"n.","book":"國八下","unit":"U2"},
    {"word":"crosswalk","def":"行人穿越道","type":"n.","book":"國八下","unit":"U2"},
    {"word":"float","def":"漂浮","type":"v.","book":"國八下","unit":"U2"},
    {"word":"red fire ant","def":"紅火蟻","type":"n.","book":"國八下","unit":"U2"},
    {"word":"stay away from","def":"遠離…","type":"phr.","book":"國八下","unit":"U2"},
    // Unit 3
    {"word":"loudly","def":"大聲地","type":"adv.","book":"國八下","unit":"U3"},
    {"word":"hard","def":"努力地；困難的","type":"adv./adj.","book":"國八下","unit":"U3"},
    {"word":"weak","def":"虛弱的","type":"adj.","book":"國八下","unit":"U3"},
    {"word":"hen","def":"母雞","type":"n.","book":"國八下","unit":"U3"},
    {"word":"dirty","def":"骯髒的","type":"adj.","book":"國八下","unit":"U3"},
    {"word":"mean","def":"刻薄的；兇惡的","type":"adj.","book":"國八下","unit":"U3"},
    {"word":"owner","def":"擁有者；主人","type":"n.","book":"國八下","unit":"U3"},
    {"word":"quickly","def":"快速地","type":"adv.","book":"國八下","unit":"U3"},
    {"word":"service","def":"服務","type":"n.","book":"國八下","unit":"U3"},
    {"word":"wise","def":"明智的","type":"adj.","book":"國八下","unit":"U3"},
    {"word":"celebrate","def":"慶祝","type":"v.","book":"國八下","unit":"U3"},
    {"word":"labor","def":"勞工","type":"n.","book":"國八下","unit":"U3"},
    {"word":"information","def":"資訊","type":"n.","book":"國八下","unit":"U3"},
    {"word":"carefully","def":"小心地","type":"adv.","book":"國八下","unit":"U3"},
    {"word":"slowly","def":"緩慢地","type":"adv.","book":"國八下","unit":"U3"},
    {"word":"badly","def":"壞地","type":"adv.","book":"國八下","unit":"U3"},
    {"word":"beautifully","def":"美麗地","type":"adv.","book":"國八下","unit":"U3"},
    {"word":"bitter","def":"苦的","type":"adj.","book":"國八下","unit":"U3"},
    {"word":"alone","def":"單獨地","type":"adv.","book":"國八下","unit":"U3"},
    {"word":"choose","def":"選擇","type":"v.","book":"國八下","unit":"U3"},
    // Unit 4
    {"word":"typhoon","def":"颱風","type":"n.","book":"國八下","unit":"U4"},
    {"word":"blow","def":"吹","type":"v.","book":"國八下","unit":"U4"},
    {"word":"balcony","def":"陽台","type":"n.","book":"國八下","unit":"U4"},
    {"word":"must","def":"必須；一定","type":"aux.","book":"國八下","unit":"U4"},
    {"word":"prepare","def":"準備","type":"v.","book":"國八下","unit":"U4"},
    {"word":"should","def":"應該","type":"aux.","book":"國八下","unit":"U4"},
    {"word":"candle","def":"蠟燭","type":"n.","book":"國八下","unit":"U4"},
    {"word":"flashlight","def":"手電筒","type":"n.","book":"國八下","unit":"U4"},
    {"word":"sway","def":"搖擺","type":"v.","book":"國八下","unit":"U4"},
    {"word":"radio","def":"收音機；廣播","type":"n.","book":"國八下","unit":"U4"},
    {"word":"suddenly","def":"突然","type":"adv.","book":"國八下","unit":"U4"},
    {"word":"fear","def":"恐懼","type":"n.","book":"國八下","unit":"U4"},
    {"word":"shelter","def":"避難收容所","type":"n.","book":"國八下","unit":"U4"},
    {"word":"rainbow","def":"彩虹","type":"n.","book":"國八下","unit":"U4"},
    {"word":"earthquake","def":"地震","type":"n.","book":"國八下","unit":"U4"},
    {"word":"rescue","def":"救援","type":"n./v.","book":"國八下","unit":"U4"},
    {"word":"survivor","def":"生還者","type":"n.","book":"國八下","unit":"U4"},
    {"word":"bravely","def":"勇敢地","type":"adv.","book":"國八下","unit":"U4"},
    {"word":"rubble","def":"瓦礫；碎石","type":"n.","book":"國八下","unit":"U4"},
    {"word":"no longer","def":"不再","type":"phr.","book":"國八下","unit":"U4"},
    // Unit 5
    {"word":"although","def":"雖然","type":"conj.","book":"國八下","unit":"U5"},
    {"word":"sore throat","def":"喉嚨痛","type":"n.","book":"國八下","unit":"U5"},
    {"word":"cough","def":"咳嗽","type":"v./n.","book":"國八下","unit":"U5"},
    {"word":"probably","def":"很可能；大概","type":"adv.","book":"國八下","unit":"U5"},
    {"word":"stand","def":"攤位","type":"n.","book":"國八下","unit":"U5"},
    {"word":"medicine","def":"藥","type":"n.","book":"國八下","unit":"U5"},
    {"word":"honey","def":"蜂蜜","type":"n.","book":"國八下","unit":"U5"},
    {"word":"lemon","def":"檸檬","type":"n.","book":"國八下","unit":"U5"},
    {"word":"recipe","def":"食譜","type":"n.","book":"國八下","unit":"U5"},
    {"word":"headache","def":"頭痛","type":"n.","book":"國八下","unit":"U5"},
    {"word":"stomachache","def":"胃痛","type":"n.","book":"國八下","unit":"U5"},
    {"word":"fever","def":"發燒","type":"n.","book":"國八下","unit":"U5"},
    {"word":"useful","def":"有用的","type":"adj.","book":"國八下","unit":"U5"},
    {"word":"helpful","def":"有幫助的","type":"adj.","book":"國八下","unit":"U5"},
    {"word":"memory","def":"記憶；記憶力","type":"n.","book":"國八下","unit":"U5"},
    {"word":"brain","def":"頭腦","type":"n.","book":"國八下","unit":"U5"},
    {"word":"blood","def":"血液","type":"n.","book":"國八下","unit":"U5"},
    {"word":"focus","def":"專注；焦點","type":"v./n.","book":"國八下","unit":"U5"},
    {"word":"common","def":"常見的；共同的","type":"adj.","book":"國八下","unit":"U5"},
    {"word":"actually","def":"實際上；事實上","type":"adv.","book":"國八下","unit":"U5"},
    {"word":"take care of","def":"照顧","type":"phr.","book":"國八下","unit":"U5"},
    {"word":"feel like","def":"想要","type":"phr.","book":"國八下","unit":"U5"},
    // Unit 6
    {"word":"throw","def":"丟；投擲","type":"v.","book":"國八下","unit":"U6"},
    {"word":"point","def":"得分","type":"n.","book":"國八下","unit":"U6"},
    {"word":"win","def":"贏；獲勝","type":"v.","book":"國八下","unit":"U6"},
    {"word":"excuse","def":"藉口；理由","type":"n.","book":"國八下","unit":"U6"},
    {"word":"member","def":"成員","type":"n.","book":"國八下","unit":"U6"},
    {"word":"fail","def":"考不及格；失敗","type":"v.","book":"國八下","unit":"U6"},
    {"word":"afraid","def":"害怕的；擔憂的","type":"adj.","book":"國八下","unit":"U6"},
    {"word":"fresh","def":"新的；新鮮的","type":"adj.","book":"國八下","unit":"U6"},
    {"word":"grade","def":"成績","type":"n.","book":"國八下","unit":"U6"},
    {"word":"mistake","def":"錯誤","type":"n.","book":"國八下","unit":"U6"},
    {"word":"allow","def":"允許","type":"v.","book":"國八下","unit":"U6"},
    {"word":"stereotype","def":"刻板印象","type":"n.","book":"國八下","unit":"U6"},
    {"word":"honest","def":"誠實的；可信的","type":"adj.","book":"國八下","unit":"U6"},
    {"word":"talent","def":"人才；天分","type":"n.","book":"國八下","unit":"U6"},
    {"word":"excellent","def":"優秀的；極佳的","type":"adj.","book":"國八下","unit":"U6"},
    {"word":"define","def":"下定義；界定","type":"v.","book":"國八下","unit":"U6"},
    {"word":"designer","def":"設計師","type":"n.","book":"國八下","unit":"U6"},
    {"word":"gender","def":"性別","type":"n.","book":"國八下","unit":"U6"},
    {"word":"relationship","def":"關係","type":"n.","book":"國八下","unit":"U6"},
    {"word":"fact","def":"事實","type":"n.","book":"國八下","unit":"U6"},
    {"word":"lead to","def":"導致","type":"phr.","book":"國八下","unit":"U6"},
    {"word":"be able to","def":"能夠","type":"phr.","book":"國八下","unit":"U6"},
    {"word":"keep in mind","def":"記住","type":"phr.","book":"國八下","unit":"U6"},
  ];
  if (window.vocabularyData) {
    window.vocabularyData = window.vocabularyData.concat(g8b);
  } else {
    window.vocabularyData = g8b;
  }
})();
